"""initial_schema

Revision ID: fb08d15f7728
Revises: 
Create Date: 2026-03-02 04:57:52.054086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb08d15f7728'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('REGULAR', 'RESPONDER', 'ADMIN', name='userrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('incident_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reporter_id', sa.String(length=36), nullable=True),
    sa.Column('location_text', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'TRIAGED', 'NEEDS_MORE_INFO', 'DISPATCHED', 'RESOLVED', 'CLOSED', name='reportstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_reports_created_at'), 'incident_reports', ['created_at'], unique=False)
    op.create_index('ix_incident_reports_lat_lng', 'incident_reports', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_incident_reports_location_text'), 'incident_reports', ['location_text'], unique=False)
    op.create_index(op.f('ix_incident_reports_reporter_id'), 'incident_reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_incident_reports_status'), 'incident_reports', ['status'], unique=False)
    op.create_table('final_triage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('incident_type', sa.Enum('VIOLENCE_FIGHT', 'FIRE_SMOKE', 'MEDICAL', 'ROAD_HAZARD', 'TRANSIT_DISRUPTION', 'SUSPICIOUS_ACTIVITY', 'OTHER', name='incidenttype'), nullable=True),
    sa.Column('final_severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('routing_target', sa.Enum('CALL_999', 'CALL_995', 'LTA', 'TOWN_COUNCIL', 'PUBLIC_ALERT_ONLY', 'NEEDS_USER_CONFIRMATION', name='routingtarget'), nullable=True),
    sa.Column('user_next_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('followup_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('responder_summary', sa.Text(), nullable=True),
    sa.Column('applied_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['incident_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_index(op.f('ix_final_triage_final_severity'), 'final_triage', ['final_severity'], unique=False)
    op.create_index(op.f('ix_final_triage_incident_type'), 'final_triage', ['incident_type'], unique=False)
    op.create_index('ix_final_triage_route_sev', 'final_triage', ['routing_target', 'final_severity'], unique=False)
    op.create_index(op.f('ix_final_triage_routing_target'), 'final_triage', ['routing_target'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', name='mediatype'), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['incident_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_media_type'), 'media_assets', ['media_type'], unique=False)
    op.create_index(op.f('ix_media_assets_report_id'), 'media_assets', ['report_id'], unique=False)
    op.create_index(op.f('ix_media_assets_sha256'), 'media_assets', ['sha256'], unique=False)
    op.create_table('text_triage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('incident_type', sa.Enum('VIOLENCE_FIGHT', 'FIRE_SMOKE', 'MEDICAL', 'ROAD_HAZARD', 'TRANSIT_DISRUPTION', 'SUSPICIOUS_ACTIVITY', 'OTHER', name='incidenttype'), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('missing_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggested_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['incident_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_index(op.f('ix_text_triage_incident_type'), 'text_triage', ['incident_type'], unique=False)
    op.create_index(op.f('ix_text_triage_severity'), 'text_triage', ['severity'], unique=False)
    op.create_index('ix_text_triage_type_sev', 'text_triage', ['incident_type', 'severity'], unique=False)
    op.create_table('vision_triage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hint_severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=True),
    sa.Column('hint_confidence', sa.Float(), nullable=True),
    sa.Column('faces_visible', sa.Boolean(), nullable=True),
    sa.Column('license_plates_visible', sa.Boolean(), nullable=True),
    sa.Column('sensitive_injury_visible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['incident_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_index('ix_vision_triage_hint_sev_conf', 'vision_triage', ['hint_severity', 'hint_confidence'], unique=False)
    op.create_index(op.f('ix_vision_triage_hint_severity'), 'vision_triage', ['hint_severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vision_triage_hint_severity'), table_name='vision_triage')
    op.drop_index('ix_vision_triage_hint_sev_conf', table_name='vision_triage')
    op.drop_table('vision_triage')
    op.drop_index('ix_text_triage_type_sev', table_name='text_triage')
    op.drop_index(op.f('ix_text_triage_severity'), table_name='text_triage')
    op.drop_index(op.f('ix_text_triage_incident_type'), table_name='text_triage')
    op.drop_table('text_triage')
    op.drop_index(op.f('ix_media_assets_sha256'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_report_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_media_type'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_final_triage_routing_target'), table_name='final_triage')
    op.drop_index('ix_final_triage_route_sev', table_name='final_triage')
    op.drop_index(op.f('ix_final_triage_incident_type'), table_name='final_triage')
    op.drop_index(op.f('ix_final_triage_final_severity'), table_name='final_triage')
    op.drop_table('final_triage')
    op.drop_index(op.f('ix_incident_reports_status'), table_name='incident_reports')
    op.drop_index(op.f('ix_incident_reports_reporter_id'), table_name='incident_reports')
    op.drop_index(op.f('ix_incident_reports_location_text'), table_name='incident_reports')
    op.drop_index('ix_incident_reports_lat_lng', table_name='incident_reports')
    op.drop_index(op.f('ix_incident_reports_created_at'), table_name='incident_reports')
    op.drop_table('incident_reports')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
